name: Java CI

on:
  push:
    branches:
    - '**'
    tags:
    - 'v*-es*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: anti-social/elasticsearch-plugin-github-action/build@856771eb28261f59a336bb363f7e4d6a54190304
      with:
        es-version: '7.9'

  release:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      startsWith(github.ref, 'refs/tags/v')
    needs:
    - build
    permissions:
      contents: write
    steps:
    - uses: anti-social/elasticsearch-plugin-github-action/release@856771eb28261f59a336bb363f7e4d6a54190304
