name: Java CI

on:
  push:
    branches:
    - '**'
    tags:
    - 'v*-es*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: anti-social/elasticsearch-plugin-github-action/build@75eac8f
